spring:
  config:
    activate:
      on-profile: local
    import: 'classpath:discord-config.yml'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/attendance
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms
        shutdown-timeout: 100ms
        client-name: auth-service
        client-options:
          connect-timeout: 3000ms  # 3초
        read-from: REPLICA_PREFERRED  # 레플리카 우선 읽기

logging:
  level:
    shop.genieus.study: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

server:
  url: http://localhost:8080