spring:
  application:
    name: server
  config:
    import: 'classpath:discord-config.yml'

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/attendance
    username: root
    password: 1234

    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms
        shutdown-timeout: 100ms
        client-name: auth-service
        client-options:
          connect-timeout: 3000ms  # 3초
        read-from: REPLICA_PREFERRED  # 레플리카 우선 읽기

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
jwt:
  secret:
    key: gP2Fc2lT54kHcFWlo2V0RcZ03YlVPuztdb8L04Rzzys=

cors:
  allowed-origins:
    - "http://localhost:3000"
    - "http://localhost:3001"
    - "https://study.genieus.shop"
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Cache-Control
    - Content-Type
  exposed-headers:
    - Authorization
    - Content-Disposition
  allow-credentials: true
  max-age: 3600
