spring:
  application:
    name: server
  profiles:
    active: local
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    root: INFO
    shop.genieus.study: INFO
    org.hibernate.SQL: INFO

jwt:
  secret:
    key: ${JWT_SECRET_KEY:gP2Fc2lT54kHcFWlo2V0RcZ03YlVPuztdb8L04Rzzys=}

cors:
  allowed-origins:
    - "http://localhost:3000"
    - "http://localhost:3001"
    - "https://study.genieus.shop"
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Cache-Control
    - Content-Type
  exposed-headers:
    - Authorization
    - Content-Disposition
  allow-credentials: true
  max-age: 3600

scheduler:
  attendance:
    system-check-out-cron: "0 0 0 * * *"  # 매일 자정에 자동 퇴실 처리
  notification:
    check-in-cron: "0 50 8 * * 1-5"       # 매일 08:50에 출석 알림 (평일)
    check-out-cron: "0 0 16 * * 1-5"      # 매일 16:00에 코어 시간 종료 알림 (평일)